# src/memory/models.py
from datetime import datetime
from sqlalchemy import Column, String, Float, Integer, DateTime, ForeignKey, Text, ARRAY
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import declarative_base, relationship
from pgvector.sqlalchemy import Vector
import uuid

Base = declarative_base()

class NationMemory(Base):
    """
    Core memory unit. Stores the vector for semantic search AND the link to the previous memory
    for narrative reconstruction.
    """
    __tablename__ = 'nation_memories'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    nation_id = Column(String(50), nullable=False)
    memory_type = Column(String(20), nullable=False) # 'observation', 'interaction', 'reflection'
    content = Column(Text, nullable=False)
    
    # 768 dimensions for Gemini text-embedding-004
    embedding = Column(Vector(768))
    
    importance = Column(Float, default=0.5)
    timestamp = Column(DateTime(timezone=True), default=datetime.utcnow)
    
    # Narrative Graph (Introduction of Linked List)
    # Allows traversing history: O(1) fetch of what happened right before this
    previous_memory_id = Column(UUID(as_uuid=True), ForeignKey('nation_memories.id'))
    cause_event_id = Column(UUID(as_uuid=True)) # E.g., ID of the news item this reacts to

    # Relationships
    previous_memory = relationship("NationMemory", remote_side=[id], backref="next_memory")

class MemoryReflection(Base):
    """
    Periodic high-level summaries generated by the agent.
    """
    __tablename__ = 'memory_reflections'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    nation_id = Column(String(50), nullable=False)
    question = Column(Text)
    answer = Column(Text)
    source_memory_ids = Column(ARRAY(UUID(as_uuid=True)))
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
